# Generated by Django 5.0.6 on 2024-07-08 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='git',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
