# Generated by Django 5.0.6 on 2024-07-08 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojects', '0002_project_git'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='preview',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
